version: "2.4"

services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      network:
        aliases:
          - proxy
    ports:
      - 8084:80
    depends_on:
      couchdb:
        condition: service_healthy
  
  authServer:
    restart: always
    environment:
      COUCHDB_URL: http://couchdb:5984
    image: authserver
    build: ./authServer
    networks:
      network:
        aliases:
          - authServer
  
  couchdb:
    restart: always
    environment:
      COUCHDB_USER: zach
      COUCHDB_PASSWORD: v6eJTCAyZ4urv2jTY
      COUCHDB_SECRET: 6xECC2e98mC55mPUs
      NODENAME: couchdb-0
      ERL_FLAGS: "-setcookie Ma88qaC6RhG3KmgMm"
    image: zachlankton/couchdb-clouseau:3.3.3.1
    networks:
      network:
        aliases:
          - couchdb
    ports:
      - "5984:5984"
    volumes:
      - "data-couch-0:/opt/couchdb/data"
      - "cfg-couch-0:/opt/couchdb/etc/local.d"
    healthcheck:
      test: curl --fail http://127.0.0.1:5984/_up || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  

networks:
  network:

volumes:
  data-couch-0:
  cfg-couch-0: